version: "3.8"

services:
  back:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app:rw,cached

      - /app/node_modules
    ports:
      - 5000:5000
    depends_on:
      - db
  db:
    image: postgres:15.1-alpine
    restart: always
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: portfolio
      POSTGRES_PASSWORD: portfolio
      POSTGRES_DB: portfolio
      PGDATA: /var/lib/postgresql/data/customDataFolder
    volumes:
      - /tmp/dbData:/var/www/html/Portfolio/Back
    ports:
      - 6002:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d portfolio -U portfolio"]
      interval: 5s
      timeout: 5s
      retries: 10
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    depends_on:
      db:
        condition: service_healthy
